apiVersion: v1
appVersion: v0.12.1
description: A Helm chart for prometheus mysql exporter with cloudsqlproxy
home: https://github.com/prometheus/mysqld_exporter
keywords:
  - exporter
maintainers:
  - email: juan.chimienti@gmail.com
    name: juanchimienti
  - email: monotek23@gmail.com
    name: monotek
  - email: support@kubegems.io
    name: KubeGems
name: prometheus-mysql-exporter
sources:
  - https://github.com/prometheus/mysqld_exporter
version: 1.8.2
