$schema: http://json-schema.org/schema#
type: object
properties:
  nameOverride:
    type: string
    title: Consul Exporter名称
    form: true
  fullnameOverride:
    type: string
    title: Consul Exporter服务名
    form: true
  consulServer:
    type: string
    title: Consul地址 <host:port>
    default: consule:80
    form: true
  serviceMonitor:
    type: object
    title: Consul 监控数据采集器设置
    form: true
    properties:
      enabled:
        type: boolean
        title: 启用自动采集器(需Prometheus Operator支持)
        default: true
        form: true
      interval:
        type: string
        title: 监控数据采样频率
        default: 30s
        form: true
        hidden:
          path: serviceMonitor/enabled
          value: false
      timeout:
        type: string
        title: 监控数据采样超时
        default: 10s
        form: true
        hidden:
          path: serviceMonitor/enabled
          value: false
  alerts:
    type: object
    title: Cassandra 告警设置(需Prometheus Operator支持)
    form: true
    properties:
      enabled:
        type: boolean
        title: 启用平台内置 Cassandra 告警规则
        default: true
        form: true
