{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: null
  labels:
    alertmanagerconfig.kubegems.io/name: {{ template "prometheus-cassandra-exporter.fullname" . }}
    alertmanagerconfig.kubegems.io/type: monitor
  name: {{ template "prometheus-cassandra-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  receivers:
  - name: "null"
  - name: gemcloud-default-webhook
    webhookConfigs:
    - httpConfig:
        tlsConfig:
          ca: {}
          cert: {}
          insecureSkipVerify: true
      url: https://kubegems-local-agent.kubegems-local:8041/alert
  route:
    groupBy:
    - gems_namespace
    - gems_alertname
    groupInterval: 30s
    groupWait: 30s
    receiver: "null"
{{- end }}