apiVersion: v2
name: prometheus-memcached-exporter
description: A Helm chart for Memecached Exporter
keywords:
- exporter 
version: 0.6.0
appVersion: "0.6.0"
maintainers:
- email: support@kubernetes.io
  name: KubeGems
