apiVersion: v1
appVersion: v0.29.0
description: Rabbitmq metrics exporter for prometheus
home: https://github.com/kbudde/rabbitmq_exporter
maintainers:
- email: cedric@desaintmartin.fr
  name: desaintmartin
- email: abhishekbhardwaj510@gmail.com
  name: iamabhishek-dubey
- email: juan.chimienti@gmail.com
  name: juanchimienti
- email: monotek23@gmail.com
  name: monotek
- email: support@kubegems.io
  name: KubeGems
name: prometheus-rabbitmq-exporter
sources:
- https://github.com/kbudde/rabbitmq_exporter
version: 1.2.0
